<div style="width: 80%">
<img src="image.png"><br>
<div style="font-size: 20pt; float: left;">Grundlagen der linearen Algebra</div>
<div style="font-size: 20pt; text-align: right;">HS 2023</div>
<div style="font-size: 15pt; margin-top: 10px;">Fachexperten: Kathrin Gerhard, Roger Burkhardt</div>
</div>
<br>


# Mini-Challenge 1 (MC1): Implementierung des Gauss-Verfahrens

**Ziel der Ãœbung**

Ziel dieser Programmierübung sind einfache Anwendungen von Python und numpy, mit dem Fokus auf die Repräsentation und Manipulation von Matrizen, womit die Studierenden in der ersten, unbewerteten Programmierübung einige erste Erfahrungen gesammelt haben sollten. Dabei soll der Gauss-Algorithmus zur Umformung einer erweiterten Koeffizientenmatrix in die Zeilenstufenform als Funktion implementiert werden, um das Verständnis für diesen zu vertiefen.

* In der ersten Aufgabe werden die elementaren Zeilenumformungen in Python implementiert. Dazu werden Python-Funktionen eingeführt und der Unterschied zwischen call-by-value und call-by-reference wird erklärt. Die Funktionen sollen die entsprechenden Slices (=Zeilen) aus Matrizen extrahieren und der Aufgabenstellung entsprechend verändern. 

* In der zweiten Aufgabe werden Sie das in der Vorlesung besprochene Gauss-Verfahren mit den in Aufgabe 1 implementierten elementaren Zeilenumformungen auf eine beispielhafte Matrix anwenden und diese in Zeilenstufenform bringen, damit Sie die Lösung des Gleichungssystems bestimmen können.

* In der dritten Aufgabe werden Sie Ihr Vorgehen in der zweiten Aufgabe formalisieren und automatisieren und eine Funktion erstellen, die mit dem Gauss-Verfahren eine Matrix für Sie automatisch in Zeilenstufenform bringt. Sie werden dabei Ihre Implementierung auf mehrere Beispielmatrizen anwenden und es auf seine korrekte Funktionsweise überprüfen.

Wir stellen Ihnen teilweise schon Teile der Implementierung zur Verfügung. Verändern Sie bitte diese Rahmengerüste nicht, sondern fügen Sie Ihren Code zwischen den Kommentaren `# IHR CODE BEGINNT HIER` und `# IHR CODE ENDET HIER` ein.

Sie dürfen in dieses Notebook über den Menüpunkt 'Insert' durchaus weitere Zeilen einfügen. Falls Sie gerne Markdown-Notizen in die Zelle einfügen möchten, können Sie den Modus der Zelle von 'Code' auf 'Markdown' setzen (oder Esc-M drücken).

## Aufgabe 1: Elementare Zeilenumformungen

Sie haben in der Vorlesung die drei elementaren Zeilenumformungen kennengelernt, die ein Gleichungssystem in seiner Repräsentation als erweiterte Koeffizientenmatrix in eine äquivalente Matrix überführen. Diese Umformungen sind

* Multiplikation einer Gleichung / Zeile der Matrix mit einem Skalar
* Vertauschen zweier Gleichungen / Zeilen der Matrix
* Addition einer Gleichung / Zeile der Matrix zu einer anderen

Im Folgenden werden Sie für jede dieser drei Zeilenumformungen eine Python-Funktionen implementieren, die sie dann auf eine beliebige Matrix anwenden können. Zum Überprüfen auf korrekte Funktionalität können Sie dabei folgende Matrix benutzen:

In [2]:
import numpy as np
A = np.matrix( [[1,1,-1,3],[1,2,-2,2],[2,-1,2,15]], dtype=np.float64 )
print( A )

[[ 1.  1. -1.  3.]
 [ 1.  2. -2.  2.]
 [ 2. -1.  2. 15.]]


### Teilaufgabe 1a): Multiplikation mit einem Skalar

Zuerst werden Sie eine Funktion implementieren, die eine beliebige Zeile einer Matrix mit einem Skalar multipliziert. Wir haben das Gerüst der Funktion (Definition, Parameter, Rückgabewert) bereits für Sie vorgegeben. [Hier](https://en.wikibooks.org/wiki/Python_Programming/Functions) finden Sie eine vertiefte Einführung in Python-Funktionen.

**Hinweis:** Beachten Sie, dass wir explizit eine Kopie der Matrix erstellen: Standardmässig übergibt Python Matrizen mit call-by-reference, d.h. alle Operationen auf der übergebenen Matrix M werden auf dem original ausgeführt, was oft effizienter ist als eine Kopie (call-by-value) zu erstellen. In diesem Fall ist es aber sauberer, die ursprüngliche Matrix nicht anzurühren, sondern eine Kopie zu machen und diese explizit zurückzugeben. Machen Sie im Folgenden wenn immer möglich eine Kopie der übergebenen Matrix.

In [3]:
def multipliziere( M, zeile, skalar ):
    """
    Multipliziert eine Zeile einer Matrix mit einem skalaren Faktor.
        
    Arguments:
    M -- Matrix mit shape (m,n)
    zeile -- Zeile, die multipliziert werden soll
    skalar -- Faktor, mit dem die Zeile multipliziert werden soll
    
    Returns:
    Matrix mit skalarem Faktor multiplizierter Zeile 
    """
    M = M.copy()
    
    # IHR CODE BEGINNT HIER
    M[zeile-1] = M[zeile-1]*skalar
    
    # IHR CODE ENDET HIER
    
    return M


Sie können nun im folgenden Feld Ihre Funktion auf der Matrix **A** auf korrekte Funktion testen:

In [5]:
# IHR CODE BEGINNT HIER
multipliziere(A, 1, 2)
# IHR CODE ENDET HIER

matrix([[ 2.,  2., -2.,  6.],
        [ 1.,  2., -2.,  2.],
        [ 2., -1.,  2., 15.]])

### Teilaufgabe 1b): Vertauschung zweier Zeilen

Nun werden Sie auf die gleiche Weise die Vertauschung zweier Zeilen implementieren.

**Hinweis**: Auch hier gilt es wieder, den Umgang von Python mit Matrzen zu beachten. Wenn Sie über den Indexoperator auf eine spezifische Zeile der Matrix zugreifen, gibt Python eine Referenz zum Speicherort dieser Zeile zurück, das ist platzsparend und sehr effizient. Das ist aber ebenfalls ein unerwünschtes Verhalten hier - verwenden Sie darum ebenfalls
M[ i,: ] = M[ j, : ].copy() wenn Sie eine Zeile einer anderen zuweisen wollen.

In [18]:
def vertausche( M, zeile1, zeile2 ):
    """
    Vertauscht zwei Zeilen einer Matrix.
        
    Arguments:
    M -- Matrix mit shape (m,n)
    zeile1 -- Erste Zeile, die vertauscht werden soll
    zeile2 -- Zweite Zeile, die vertauscht werden soll
    
    Returns:
    Matrix mit vertauschten Zeilen
    """
    M = M.copy()
    
    # IHR CODE BEGINNT HIER
    x = M[zeile1-1].copy()
    M[zeile1-1] = M[zeile2-1]
    M[zeile2-1] = x
    # IHR CODE ENDET HIER

    return M

Test der Funktion

In [19]:
B = np.arange(9).reshape(3,3)

# IHR CODE BEGINNT HIER
vertausche(B, 1, 2)
# IHR CODE ENDET HIER

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### Teilaufgabe 1c): Ersetzen einer Zeile durch eine nicht-triviale Linearkombination dieser Zeile mit einer anderen Zeile

Mit den Kenntnissen aus den ersten beiden Teilaufgaben sollten Sie nun auch die letzte Funktion implementieren können:

In [20]:
def ersetze( M, ziel_zeile, skalar1, zeile2, skalar2):
    """
    Ersetzt die ziel_zeile durch die Linearkombination skalar1*ziel_zeile+skalar2*zeile2.
        
    Arguments:
    M -- Matrix mit shape (m,n)
    ziel_zeile -- Zeile, in die das Resultat gespeichert werden soll
    skalar1 -- Multiplikationsfaktor der ziel_zeile
    zeile2 -- Zeile, deren Vielfaches addiert werden soll
    skalar2 -- Multiplikationsfaktor der zweiten Zeile
    
    Returns:
    Matrix mit addierten Zeilen
    """
    M = M.copy()
    
    # IHR CODE BEGINNT HIER
    M[ziel_zeile-1] = M[ziel_zeile-1] * skalar1 + M[zeile2-1] * skalar2 
    
    # IHR CODE ENDET HIER
    
    return M

Test der Funktion:

In [21]:
# IHR CODE BEGINNT HIER
ersetze(B,3, 1, 2, 1)

# IHR CODE ENDET HIER

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 11, 13]])

## Aufgabe 2: Manuelle Durchführung des Gauss-Verfahrens

Nun haben Sie alle möglichen Zeilenumformungen, welche die Lösungsmenge eines linearen Gleichungssystem (und damit seine erweiterte Koeffizientenmatrix) unverändert lassen, als Python-Funktionen implementiert.

### Teilaufgabe 2a): Anwendung der Zeilenumformungen

Bringen Sie die Matrix **B** durch elementare Zeilenumformungen auf Zeilenstufenform:

In [22]:
B = np.matrix( [[0,1,-1,3],[1,2,-2,2],[2,-1,2,15]], dtype=np.float64 )
print( B )

[[ 0.  1. -1.  3.]
 [ 1.  2. -2.  2.]
 [ 2. -1.  2. 15.]]


Benutzen Sie dazu für jede neue Umformung eine neue Jupyter-Zelle. Speichern Sie das Resultat der Zeilenumformung jeweils in B (z.B. `B = addiere( B, ... )`) und geben Sie die umgeformte Matrix jeweils mit `print( B )` aus.

In [23]:
# IHR CODE BEGINNT HIER
B = vertausche(B, 1, 2)
B

matrix([[ 1.,  2., -2.,  2.],
        [ 0.,  1., -1.,  3.],
        [ 2., -1.,  2., 15.]])

In [24]:
B = ersetze(B, 3, 1, 1, -2)
B

matrix([[ 1.,  2., -2.,  2.],
        [ 0.,  1., -1.,  3.],
        [ 0., -5.,  6., 11.]])

In [25]:
B = ersetze(B, 3, 1, 2, 5)
B

matrix([[ 1.,  2., -2.,  2.],
        [ 0.,  1., -1.,  3.],
        [ 0.,  0.,  1., 26.]])

In [26]:
B = ersetze(B, 2, 1, 3, 1)
B
# IHR CODE ENDET HIER

matrix([[ 1.,  2., -2.,  2.],
        [ 0.,  1.,  0., 29.],
        [ 0.,  0.,  1., 26.]])

In [27]:
B = ersetze(B, 1, 1, 2, -2)
B

matrix([[  1.,   0.,  -2., -56.],
        [  0.,   1.,   0.,  29.],
        [  0.,   0.,   1.,  26.]])

In [28]:
B= ersetze(B, 1, 1, 3, 2)
B

matrix([[ 1.,  0.,  0., -4.],
        [ 0.,  1.,  0., 29.],
        [ 0.,  0.,  1., 26.]])

### Teilaufgabe 2b): Lösung durch Rückwärtssubstitution

Berechnen Sie die Lösung des durch die Matrix **B** repräsentierten Gleichungssystems durch Rückwärtssubstitution und geben Sie die Lösungsmenge in der nächsten Zelle im Markdown-Format an:

In [32]:
# IHR CODE BEGINNT HIER
x1 = B[0,3]
x2 = B[1,3]
x3 = B[2,3]
print(f'x = {x1}, y = {x2}, z = {x3}')
# IHR CODE ENDET HIER

x = -4.0, y = 29.0, z = 26.0


L=???

## Aufgabe 3: Implementierung des Gauss-Verfahrens

### Teil a): Implementierung des Gauss-Verfahrens

Wir möchten nun unser Vorgehen aus Aufgabe 2 automatisieren. Implementieren Sie eine Funktion `gauss_elimination`, die für eine beliebige Matrix **M** das Gauss-Verfahren durchführt und sie damit auf Zeilenstufenform bringt. Wir stellen Ihnen dabei den Gauss-Algorithmus als Pseudocode zur Verfügung. Versuchen Sie diesen Pseudecode mit der Vorlesung in Bezug zu setzen und setzen Sie ihn in eine Python-Implementation um, indem Sie die in Aufgabe 1 implementierten Funktionen verwenden.

<font size = 5>
<hr style="height: 5px">
<b>Pseudocode für das Gauss-Verfahren</b>
<hr style="height: 5px">


<ul style="line-height: 1.4">
    <li>setze m = Anzahl Zeilen der Matrix M und n = Anzahl Spalten der Matrix M</li>
    <li>setze i, j = 0</li>
    <li>solange i<m und j<n:</li>
    <ul>
        <li>setze l = -1</li>
        <li>für k = i, .., m:</li>
        <ul>
            <li>falls |M[k,j])| > 0:</li>
            <ul>
                <li>l = k</li>
                <li>beende die Schleife frühzeitig</li>
            </ul>
        </ul>
        <li>falls l >= 0:</li>
            <ul>
                <li>falls i $\neq$ l:</li>
                <ul>
                    <li>vertausche die Zeilen i und l</li>
                </ul>
                <li>dividiere die Zeile i durch M[i,j]</li>
                <li>für u = i+1, .., m:</li>
                <ul><li>subtrahiere M[u,j] mal die i-te Zeile von der u-ten Zeile</li></ul>
                <li>inkrementiere i = i+1</li>
        </ul>
        <li>inkrementiere j = j+1</li>
     </ul>  
</ul>          
<hr style="height: 5px">

Sie benötigen für diese Funktion die Kontrollstrukturen von Python (`for`, `if` und `while`) und ausserdem die `range`-Funktion, die Ihnen eine Liste von Zahlen zurückgibt, über die Sie mit `for` iterieren können. Ausserdem kann Ihnen die Anweisung `break` helfen, die eine Schleife in ihrer Ausführung vorzeitig abbricht.

In [ ]:
def gauss_elimination( M, print_steps=True ):
    """
    Bringt die Matrix M mittels dem Gauss-Verfahren auf Zeilenstufenform
        
    Arguments:
    M -- Matrix mit shape (m,n)
    print_steps -- Gibt einzelne Berechnungsschritte aus falls True
    
    Returns:
    Matrix in Zeilenstufenform
    """
    M = M.copy()
    m, n = M.shape
    m = m+1
    n = n+1

    # IHR CODE STARTET HIER
    
    
    # IHR CODE ENDET HIER
    
    return M

### Teil b): Anwendung Ihrer Implementierung auf ausgewählte Matrizen

Weiterhin stellen wir Ihnen eine Reihe von Matrizen zur Verfügung, auf denen Sie Ihre Implementierung testen können. Berechnen Sie die einzelnen Schritte der Umwandlung in die Zeilenstufenform von Hand, dann können Sie sie mit den Schritten Ihrer Funktion vergleichen, wenn Sie `print_steps=True` verwenden.

In [ ]:
A = np.matrix( [[1,1,-1,3],[1,2,-2,2],[2,-1,2,15]], dtype=np.float64 )
print( A )

In [ ]:
# IHR CODE


In [ ]:
B = np.matrix( [[0,1,-1,3],[1,2,-2,2],[2,-1,2,15]], dtype=np.float64 )
print( B )

In [ ]:
# IHR CODE


In [ ]:
C = np.matrix( [[1,2,3,4],[5,6,7,8]], dtype=np.float64 )
print(C)

In [ ]:
# IHR CODE


In [ ]:
D = np.matrix( [[1,2],[3,4],[6,8]], dtype=np.float64 )
print(D)

In [ ]:
# IHR CODE


In [ ]:
E = np.array([[0,0,1,2,3],[0,0,7,14,11],[0,0,7,14,12]], dtype=np.float64 )
print(E)

In [ ]:
# IHR CODE


In [ ]:
F = np.array([[0,1,2,3,4],[0,0,1,7,8],[0,0,0,1,11],[0,0,0,0,1]], dtype=np.float64 )
print(F)

In [ ]:
# IHR CODE


**Kommentare**

Gerne dürfen Sie Kommentare zu Ihrer Funktion (wie sie funktioniert, was sie kann, was sie nicht kann) in eine Markdown-Zelle schreiben, indem Sie die untenstehende Zeile doppelklicken und anpassen. So können Sie je nachdem zusätzliche Teilpunkte erreichen.

Formatierungsbeispiele (bitte entfernen):

*kursiver Text*

**fetter Text**

`python_funktion()`

Aufzählung:
* 1
* 2
* 3

# Freiwillige Zusatzaufgaben

Die freiwilligen Zusatzaufgaben sind nicht mehr Teil des Mini-Challenge und geben keine Punkte. Trotzdem können Sie (falls Sie Zeit dazu haben) damit noch viel zum Thema dazulernen und sicherstellen, dass Sie alles verstanden haben.

## Zusatz 1: Rang einer Matrix bestimmen (einfach)

Implementieren Sie eine Funktion `rang( M )`, die den Rang einer Matrix `M` aus deren Zeilenstufenform (über `gauss_elimination`) bestimmt.

**Hinweis**: Die Funktionen np.sum(), np.any() oder np.all() können dabei sehr hilfreich sein.

In [ ]:
# IHR CODE

## Zusatz 2: Gauss-Jordan-Verfahren -  Implementierung der Rückwärtssubstitution

Implementieren Sie nun eine Funktion `gauss_jordan`, die eine Matrix mit `gauss_elimination` in Zeilenstufenform bringt und danach mit Rücksubstitution die Matrix auf die reduzierte Zeilenstufenform bringt. Diese Aufgabe ist nun etwas schwieriger als Aufgabe 3, da Sie nur noch den unten aufgeführten Hinweis bekommen. Wenden Sie die Funktion auf die Matrizen <b>A</b> bis <b>F</b> an.

**Hinweis zum Algorithmus**:
Verwenden Sie einen *Pivot*, d.h. eine Position in der Matrix dargestellt mit den Variablen `i` und `j`. Starten Sie ganz unten links in der Matrix und bewegen Sie den Pivot Schritt um Schritt nach rechts. Wenn Sie die erste 1 sehen (in der Matrix in Zeilenstufenform), addieren Sie passende vielfache der aktuellen Zeile zu allen oberen Zeilen und starten eine Zeile weiter oben wieder ganz links und iterieren nach rechts, bis Sie alle Zeilen abgearbeitet haben. Sie sollten auch den Fall berücksichtigen, wenn eine Zeile nur aus Nullen besteht - dann müssen Sie am Ende der Zeile mit dem Pivot einfach an den Anfang der Zeile obendran springen.

In [ ]:
# IHR CODE

## Zusatz 3: Solve-Funktion mit Fallunterscheidung

Schreiben Sie eine Funktion solve( M ), die die Matrix $M$ mittels dem Gauss-Jordan-Verfahren in die reduzierte Zeilenstufenform bringt und anschliessend entweder falls möglich ein Lösungstupel zurückgibt oder eine Meldung generiert, dass das System unendlich viele oder keine Lösungen besitzt.

In [ ]:
# IHR CODE